#!/usr/bin/env python3
"""Assemble pinned DACH_TRON2A, the user's printed adapter, and two Revo3 hands.

Run convert_adapter.py first. Vendor models and the user's original 3MF are
never modified. Generated URDFs and manifests are reproducible build outputs.
"""
import argparse
import copy
import hashlib
import json
from pathlib import Path
import shutil
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
TRON = ROOT / "vendor/tron2-robot-description/tron2a/DACH_TRON2A"
HANDS = ROOT / "vendor/brainco-revo3/revo3_system"


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def numbers(values):
    return " ".join(format(float(v), ".12g") for v in values)


def write_xml(root, path):
    ET.indent(root, space="  ")
    ET.ElementTree(root).write(path, encoding="utf-8", xml_declaration=True)


def add_fixed(robot, name, parent, child, transform):
    joint = ET.SubElement(robot, "joint", name=name, type="fixed")
    ET.SubElement(joint, "parent", link=parent)
    ET.SubElement(joint, "child", link=child)
    ET.SubElement(joint, "origin", xyz=numbers(transform["xyz_m"]), rpy=numbers(transform["rpy_rad"]))
    return joint


def color_visuals(link, rgba):
    for visual in link.findall("visual"):
        for material in list(visual.findall("material")):
            visual.remove(material)
        material = ET.SubElement(visual, "material", name=link.get("name") + "_material")
        ET.SubElement(material, "color", rgba=rgba)


def copy_meshes(link, source_base, dest_prefix, source_kind, manifest):
    for mesh in link.findall(".//mesh"):
        filename = mesh.get("filename")
        if source_kind == "tron2":
            source = source_base / "meshes" / Path(filename).name
            relative = Path(dest_prefix) / source.name
        else:
            source = (source_base / "urdf" / filename).resolve()
            local = source.relative_to(source_base / "meshes")
            # MuJoCo's URDF importer interns meshes by filename stem even when
            # strippath=false. Left/right palm base_link and part_000 aliases
            # must therefore be made globally unique in the canonical URDF.
            unique_name = dest_prefix + "__" + "__".join(local.parts)
            relative = Path(dest_prefix) / local.parent / unique_name
        if not source.is_file():
            raise FileNotFoundError(source)
        dest = ROOT / "meshes" / relative
        dest.parent.mkdir(parents=True, exist_ok=True)
        if not dest.exists() or sha(source) != sha(dest):
            shutil.copy2(source, dest)
        mesh.set("filename", "../meshes/" + relative.as_posix())
        manifest[str(dest.relative_to(ROOT))] = {"source": str(source.relative_to(ROOT)), "sha256": sha(dest)}


def build(config, config_path):
    adapter_report_path = ROOT / "meshes/adapter/adapter_report.json"
    adapter = json.loads(adapter_report_path.read_text())
    for actual, expected, label in [
        (adapter["print_scale"], config["adapter_print_scale"], "adapter print scale"),
        (adapter["mounting_reference_nominal_mm"], config["adapter_datum_nominal_mm"], "adapter datum"),
        (adapter["density_kg_m3"], config["adapter_density_kg_m3"], "adapter density"),
    ]:
        if actual != expected:
            raise ValueError(f"{label} differs between assembly config and converted geometry")
    adapter_mesh = ROOT / "meshes/adapter/adapter_visual.stl"
    if sha(adapter_mesh) != adapter["output_sha256"]:
        raise ValueError("Adapter visual mesh hash mismatch")
    collision_manifest_path = ROOT / "meshes/adapter/collision_manifest.json"
    if not collision_manifest_path.exists():
        raise FileNotFoundError("Run build_adapter_collision.py before assembling")
    collision_manifest = json.loads(collision_manifest_path.read_text())
    if collision_manifest["source_sha256"] != sha(adapter_mesh):
        raise ValueError("Adapter collision proxies are stale")

    robot = ET.Element("robot", name=config["robot_name"])
    robot.append(ET.Comment("Generated by scripts/build_description.py; edit config/assembly.json, not this file."))
    robot.append(ET.Comment("Prototype assembly. Mount transforms inferred from geometry; not physically calibrated."))
    mujoco = ET.SubElement(robot, "mujoco")
    ET.SubElement(mujoco, "compiler", strippath="false", discardvisual="false", fusestatic="false")
    ET.SubElement(robot, "link", name="world")
    add_fixed(robot, "world_to_base", "world", "base_Link", config["world_to_base"])
    mesh_manifest = {}
    modifications = []
    sources = {}
    tron_urdf = TRON / "urdf/robot.urdf"
    sources[str(tron_urdf.relative_to(ROOT))] = sha(tron_urdf)
    removed_links = {"grasper_L_Link", "grasper_R_Link"}
    for node in ET.parse(tron_urdf).getroot():
        if node.tag == "link" and node.get("name") not in removed_links:
            link = copy.deepcopy(node)
            copy_meshes(link, TRON, "tron2", "tron2", mesh_manifest)
            color_visuals(link, "0.22 0.27 0.32 1")
            robot.append(link)
        elif node.tag == "joint" and node.find("child").get("link") not in removed_links:
            robot.append(copy.deepcopy(node))
    modifications.append("Removed original grasper_L/R_Link and their fixed joints; preserved all 16 TRON2 actuated joints.")
    modifications.append("Omitted source simulator-specific gazebo/transmission blocks; retained geometry, inertia, axes and limits.")
    modifications.append("Prefixed generated Revo3 mesh basenames with full source path to prevent left/right aliases in URDF importers; mesh bytes remain unchanged.")

    for side in ("left", "right"):
        name = side + "_adapter_link"
        link = ET.SubElement(robot, "link", name=name)
        inertial = ET.SubElement(link, "inertial")
        ET.SubElement(inertial, "origin", xyz=numbers(adapter["center_mass_m"]), rpy="0 0 0")
        ET.SubElement(inertial, "mass", value=format(adapter["mass_kg"], ".12g"))
        mat = adapter["inertia_kg_m2"]
        ET.SubElement(inertial, "inertia", **{key: format(mat[i][j], ".12g") for key, i, j in [("ixx",0,0),("ixy",0,1),("ixz",0,2),("iyy",1,1),("iyz",1,2),("izz",2,2)]})
        visual = ET.SubElement(link, "visual")
        ET.SubElement(ET.SubElement(visual, "geometry"), "mesh", filename="../meshes/adapter/adapter_visual.stl")
        color_visuals(link, "0.94 0.43 0.12 1")
        for proxy in collision_manifest["pieces"]:
            path = ROOT / proxy["path"]
            if sha(path) != proxy["sha256"]:
                raise ValueError("Adapter collision proxy hash mismatch")
            collision = ET.SubElement(link, "collision", name=side + "_" + path.stem)
            ET.SubElement(ET.SubElement(collision, "geometry"), "mesh", filename="../" + proxy["path"])
        add_fixed(robot, side + "_adapter_mount", config[side]["parent_link"], name, config[side]["wrist_to_adapter"])
        hand_urdf = HANDS / "urdf" / ("revo3_" + side + ".urdf")
        sources[str(hand_urdf.relative_to(ROOT))] = sha(hand_urdf)
        for node in ET.parse(hand_urdf).getroot():
            if node.tag == "link" and node.get("name") != "world":
                hand_link = copy.deepcopy(node)
                # These fixed frames are telemetry markers, not rigid bodies.
                # Their placeholder inertia is nonphysical in the source model.
                if node.get("name") == side + "_palm" or node.get("name").endswith("_tip_Link"):
                    for inertial_node in list(hand_link.findall("inertial")):
                        hand_link.remove(inertial_node)
                    modifications.append("Removed placeholder inertial on fixed marker " + node.get("name"))
                copy_meshes(hand_link, HANDS, "revo3", "hand", mesh_manifest)
                color_visuals(hand_link, "0.82 0.86 0.89 1")
                robot.append(hand_link)
            elif node.tag == "joint" and node.get("name") != side + "_hand_base_joint":
                robot.append(copy.deepcopy(node))
        add_fixed(robot, side + "_hand_base_joint", name, side + "_hand_base_link", config[side]["adapter_to_hand"])

    urdf_dir = ROOT / "urdf"
    urdf_dir.mkdir(exist_ok=True)
    output = urdf_dir / "tron2_dach_revo3.urdf"
    write_xml(robot, output)
    ros_robot = copy.deepcopy(robot)
    for mesh in ros_robot.findall(".//mesh"):
        mesh.set("filename", mesh.get("filename").replace("../meshes/", "package://tron2_revo3_description/meshes/"))
    write_xml(ros_robot, urdf_dir / "tron2_dach_revo3.ros.urdf")

    active = [joint for joint in robot.findall("joint") if joint.get("type") != "fixed"]
    if len(active) != 58:
        raise ValueError(f"Expected 58 actuated joints, got {len(active)}")
    groups = {
        "head": [j.get("name") for j in active if j.get("name").startswith("head_")],
        "left_arm": [j.get("name") for j in active if "_L_Joint" in j.get("name")],
        "right_arm": [j.get("name") for j in active if "_R_Joint" in j.get("name")],
        "left_hand": [j.get("name") for j in active if j.get("name").startswith("left_")],
        "right_hand": [j.get("name") for j in active if j.get("name").startswith("right_")],
    }
    joint_map = {"schema": "tron2_revo3_joint_map_v1", "units": "radian", "groups": groups,
                 "joints": [{"name": j.get("name"), "axis": j.find("axis").get("xyz"), "limit": j.find("limit").attrib} for j in active],
                 "note": "Name-based kinematic model order only; not a hardware bus or SDK motor index map."}
    (ROOT / "config/joint_map.json").write_text(json.dumps(joint_map, indent=2) + "\n")
    mesh_manifest["meshes/adapter/adapter_visual.stl"] = {"source": adapter["source"], "sha256": sha(adapter_mesh)}
    for proxy in collision_manifest["pieces"]:
        mesh_manifest[proxy["path"]] = {"source": "meshes/adapter/adapter_visual.stl", "sha256": proxy["sha256"]}
    reports = ROOT / "reports"
    reports.mkdir(exist_ok=True)
    report = {"schema": "tron2_revo3_assembly_manifest_v1", "urdf": str(output.relative_to(ROOT)), "urdf_sha256": sha(output),
              "config_path": str(config_path.resolve()), "config_sha256": sha(config_path), "source_urdfs": sources,
              "builder_sha256": sha(Path(__file__)),
              "adapter_report_sha256": sha(adapter_report_path), "sources": mesh_manifest,
              "counts": {"links": len(robot.findall("link")), "joints": len(robot.findall("joint")), "actuated": len(active), "mesh_files": len(mesh_manifest)},
              "mount_status": config["mount_status"], "modifications": modifications,
              "validation_boundary": "Assembled model; not calibrated hardware, validated grasping, or full collision coverage."}
    (reports / "assembly_manifest.json").write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n")
    print(json.dumps({"urdf": str(output), "counts": report["counts"], "groups": {k:len(v) for k,v in groups.items()}}, indent=2))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=ROOT / "config/assembly.json")
    args = parser.parse_args()
    build(json.loads(args.config.read_text()), args.config)


if __name__ == "__main__":
    main()
